2024-12-12 22:43:05,534 - OrderSystem - INFO - Logging system initialized
2024-12-12 22:43:05,537 - OrderSystem - INFO - Starting generate_order_form
2024-12-12 22:43:05,537 - OrderSystem - INFO - Initializing OrderSelectionDialog
2024-12-12 22:43:05,587 - OrderSystem - INFO - Initializing database connection in dialog...
2024-12-12 22:43:06,232 - OrderSystem - INFO - Database session created successfully in dialog
2024-12-12 22:43:06,241 - OrderSystem - INFO - Loading orders from database
2024-12-12 22:43:06,373 - OrderSystem - INFO - Found 80 băng keo orders and 0 trục in orders
2024-12-12 22:43:06,387 - OrderSystem - INFO - Orders loaded successfully
2024-12-12 22:43:06,408 - OrderSystem - INFO - OrderSelectionDialog initialized successfully
2024-12-12 22:43:08,865 - OrderSystem - INFO - Confirming order selection
2024-12-12 22:43:08,865 - OrderSystem - INFO - Selected orders: ['BK-12-24-056', 'BK-12-24-046']
2024-12-12 22:43:08,865 - OrderSystem - INFO - Initializing database connection for preview
2024-12-12 22:43:09,525 - OrderSystem - INFO - Showing preview dialog
2024-12-12 22:43:18,659 - OrderSystem - INFO - Generating PDF
2024-12-12 22:43:18,664 - OrderSystem - ERROR - Error processing orders: [Errno 13] Permission denied: 'order.pdf'
Traceback (most recent call last):
  File "c:\Users\PC\Documents\scr\report_gen.py", line 539, in process_selected_orders
    create_order_pdf('order.pdf', preview.result)
  File "c:\Users\PC\Documents\scr\report_gen.py", line 288, in create_order_pdf
    doc.build(story)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\reportlab\platypus\doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\reportlab\platypus\doctemplate.py", line 1108, in build
    self._endBuild()
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\reportlab\platypus\doctemplate.py", line 1043, in _endBuild
    if getattr(self,'_doSave',1): self.canv.save()
                                  ^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\reportlab\pdfgen\canvas.py", line 1286, in save
    self._doc.SaveToFile(self._filename, self)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\reportlab\pdfbase\pdfdoc.py", line 208, in SaveToFile
    f = open(filename, "wb")
        ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'order.pdf'
2024-12-12 22:43:30,074 - OrderSystem - INFO - Confirming order selection
2024-12-12 22:43:30,074 - OrderSystem - INFO - Selected orders: ['BK-12-24-063', 'BK-12-24-061', 'BK-12-24-056', 'BK-12-24-046']
2024-12-12 22:43:30,074 - OrderSystem - INFO - Initializing database connection for preview
2024-12-12 22:43:30,771 - OrderSystem - INFO - Showing preview dialog
2024-12-12 22:43:39,083 - OrderSystem - INFO - Generating PDF
2024-12-12 22:43:40,245 - OrderSystem - INFO - PDF generated successfully
2024-12-12 22:43:40,312 - OrderSystem - INFO - Order form generation completed
